### ISSUE TITLE
@data not updating 

### ISSUE THREAD

**Issue by hovancik** [boesemar/zonefile#4]
here's what I am doing: 

```ruby

zf = Zonefile.new('@ IN SOA ns1.aaaaa.com. hostmaster.aaaaacz. 2000000000 10800 3600 604800 3600@ IN MX 10 email.aaaaa.cz. @ IN MX 20 email2.aaaaa.cz.')

zf.mx = [
      {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>1, :host=>"aspmx.l.google.com."},
      {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>5, :host=>"alt1.aspmx.l.google.com."},
      {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>5, :host=>"alt2.aspmx.l.google.com."},
      {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>10, :host=>"alt3.aspmx.l.google.com."},
      {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>10, :host=>"alt4.aspmx.l.google.com."}
    ]

p zf
```
output is: 

```ruby
 #<Zonefile:0x007fcfc1eddee0
 @data="@ IN SOA ns1.aaaaa.com. hostmaster.aaaaacz. 2000000000 10800 3600 604800 3600@ IN MX 10 email.aaaaa.cz. @ IN MX 20 email2.aaaaa.cz.",
 @filename=nil,
 @origin="",
 @records=
  {:mx=>
    [{:name=>"@", :ttl=>nil, :class=>"IN", :pri=>1, :host=>"aspmx.l.google.com."},
     {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>5, :host=>"alt1.aspmx.l.google.com."},
     {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>5, :host=>"alt2.aspmx.l.google.com."},
     {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>10, :host=>"alt3.aspmx.l.google.com."},
     {:name=>"@", :ttl=>nil, :class=>"IN", :pri=>10, :host=>"alt4.aspmx.l.google.com."}],
   :a=>[],
   :a4=>[],
   :ns=>[],
   :cname=>[],
   :txt=>[],
   :ptr=>[],
   :srv=>[],
   :soa=>[],
   :ds=>[],
   :dnskey=>[],
   :rrsig=>[],
   :nsec=>[],
   :nsec3=>[],
   :nsec3param=>[],
   :naptr=>[]},
 @soa={:origin=>"@", :ttl=>"", :primary=>"ns1.aaaaa.com.", :email=>"hostmaster.aaaaacz.", :serial=>"2000000000", :refresh=>"10800", :retry=>"3600", :expire=>"604800", :minimumTTL=>"3600"}>
```

I believe the @data are not OK?

**Comment by boesemar** [comment]
you don't have newlines in the string you pass to Zonefile.new, try:

"@ IN SOA ns1.aaaaa.com. hostmaster.aaaaacz. 2000000000 10800 3600 604800 3600\n@ IN MX 10 email.aaaaa.cz. \n@ IN MX 20 email2.aaaaa.cz."

Then for the data of the modified zonefile use the 'output' method:

print zf.output

**Comment by hovancik** [comment]
@boesemar 
yes, you are right, but data do not get updated. they stay the old value: `@data="@ IN SOA ns1.aaaaa.com. hostmaster.aaaaacz. 2000000000 10800 3600 604800 3600\n@ IN MX 10 email.aaaaa.cz. \n@ IN MX 20 email2.aaaaa.cz.",` 

zf.output is with extras that I do not need. what I am looking for is what data gives me, but I would expect it to get updated with new mx values that I passed in.

**Comment by boesemar** [comment]
@data isn't supposed to change.... if you require a different format (without the extras) I am afraid that the only way is to monkey patch the output-method.

**Comment by hovancik** [comment]
ok, thanks. 

for reference: if anyone has similar issues with `Zonefile#output` not working for them, I have forked it and created `Zonefile#dump`. Might work for you as well.  https://github.com/hovancik/zonefile
